### ISSUE TITLE
is it an error for the line 297 in "novelty_detector.py"

### ISSUE THREAD

**Issue by miaozhang0525** [podgorskiy/GPND#6]
When you calculate logD = np.sum(np.log(np.abs(s))) # | \mathrm{det} S^{-1} |
is that should be logD = **-**np.sum(np.log(np.abs(s))) # | \mathrm{det} S^{-1} |

Because you are calculating the inverse of the matrix.

**Comment by HelloSeeing** [comment]
It is because $J$ is the Jacobian of the encoder ```g``` rather than the generator ```f```, and $$g \approx f^{-1}$$

**Comment by miaozhang0525** [comment]
> It is because $J$ is the Jacobian of the encoder `g` rather than the generator `f`, and $$g \approx f^{-1}$$

Hi, HelloSeeing,

Really thanks for your explanation. I got it!!
